apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webshop

resources:
- deployment.yaml

commonLabels:
  app.kubernetes.io/name: webshop
  app.kubernetes.io/managed-by: kustomize
