apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webshop

bases:
- ../../base

namePrefix: staging-

replicas:
- name: webshop-app
  count: 3

images:
- name: harbor.webshop.example.com/webshop/webshop-app
  newTag: latest

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: webshop-app
  spec:
    template:
      spec:
        containers:
        - name: webshop
          env:
          - name: ENVIRONMENT
            value: "staging"
          - name: LOG_LEVEL
            value: "debug"

configMapGenerator:
- name: webshop-config
  literals:
  - ENVIRONMENT=staging
  - LOG_LEVEL=debug
